/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package frames;

import java.awt.BorderLayout;
import java.awt.Component;
import java.awt.Dimension;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import javax.swing.Box;
import javax.swing.BoxLayout;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JMenuItem;
import javax.swing.JPanel;
import javax.swing.JPopupMenu;
import javax.swing.JScrollPane;
import javax.swing.SwingConstants;

/**
 *
 * @author Luis
 */
public class TelaHomeAluno extends javax.swing.JPanel {
    private MainFrame mainFrame;
    private JPanel panelCards;
    private JScrollPane scrollPane;
    private JPopupMenu menuPopup;

    public TelaHomeAluno(MainFrame mainFrame) {
        this.mainFrame = mainFrame;
        setSize(1080, 900);
        setLayout(new BorderLayout());

        // Painel Superior
        JPanel topPanel = new JPanel();
        topPanel.setPreferredSize(new Dimension(1080, 100));
        topPanel.setLayout(new BorderLayout());
        JLabel labelTitulo = new JLabel("ESTUDAAI", SwingConstants.CENTER);
        labelTitulo.setSize(new Dimension(200, 100));
        topPanel.add(labelTitulo, BorderLayout.CENTER);

        // Ícone de menu e ação
        JLabel menuLabel = new JLabel("MENU"); // Defina o caminho do seu ícone de menu
        menuLabel.addMouseListener(new MouseAdapter() {
            @Override
            public void mouseClicked(MouseEvent e) {
                mostrarMenu(e.getComponent(), e.getX(), e.getY());
            }
        });
        topPanel.add(menuLabel, BorderLayout.WEST);

        add(topPanel, BorderLayout.NORTH);

        // Configuração dos cards
        panelCards = new JPanel();
        panelCards.setLayout(new BoxLayout(panelCards, BoxLayout.Y_AXIS));
        scrollPane = new JScrollPane(panelCards,
            JScrollPane.VERTICAL_SCROLLBAR_AS_NEEDED,
            JScrollPane.HORIZONTAL_SCROLLBAR_NEVER);
        add(scrollPane, BorderLayout.CENTER);

        // Adicionando cards
        adicionarCards();
    }

    private void mostrarMenu(Component component, int x, int y) {
        if (menuPopup == null) {
            menuPopup = new JPopupMenu();
            JMenuItem menuItemSair = new JMenuItem("Sair");
            menuItemSair.addActionListener(e -> mainFrame.showCard("Login"));
            menuPopup.add(menuItemSair);
        }
        menuPopup.show(component, x, y);
    }

    private void adicionarCards() {
        // Exemplo de adicionar cards
        for (int i = 0; i < 10; i++) {
            TutorCard card = new TutorCard("Tutor " + (i + 1), "Matemática", "Contactar");
            panelCards.add(card);
            panelCards.add(Box.createRigidArea(new Dimension(0, 10))); // Espaço entre cards
        }
        panelCards.revalidate();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 802, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 483, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
